cacheFolder: .yarn/berry/cache
# npm 官方源
#npmRegistryServer: "https://registry.npmjs.org/"
# 淘宝源
npmRegistryServer: "https://registry.npmmirror.com/"
# 腾讯源
#npmRegistryServer: "https://mirrors.cloud.tencent.com/npm/"
# 华为云源
#npmRegistryServer: "https://repo.huaweicloud.com/repository/npm/"
